[workspace]
members = ["rapier2d", "rapier3d"]

[profile.release]
debug = false
codegen-units = 1
#lto = true

[patch.crates-io]
rapier2d = { path = "../rapier/build/rapier2d" }
rapier3d = { path = "../rapier/build/rapier3d" }
parry2d = { path = "../parry/build/parry2d" }
parry3d = { path = "../parry/build/parry3d" }
#simba = { path = "../simba" }
